### PR TITLE
Use magister.js getter/setters

### PR DESCRIPTION
**Pull request by lieuwex**
Currently Magister.js uses a getter/setters (we want to remove those, see https://github.com/simplyGits/MagisterJS/issues/15), using getter/setters now will give 2 advantages:
- Magister.js does some sanitzing, so you don't have to do that yourself
- It's slightly easier to switch to non getter/setter style when we implement that.

### CODE REVIEW

**Comment by lieuwex** [comment]
I must say, I didn't test the code whatsoever, so I hope I didn't fuck up anywhere.

**Comment by lesander** [comment]
Hey @lieuwex thanks for the heads up, I wasn't aware of the deprecated `_`'s. I'll do some testing and see if the program still works with your changes.

**Comment by lesander** [comment]
Hey @lieuwex, I've tested your code, and it seems to be working just fine, although there seems to be a difference with `_content` parsed by Magister Calendar (using replaces and such), and the parsed content `content()` returns. 

Please re-base your pull request branch to `1.4.1` and then I'll merge. Thanks again for the contribution!

**Comment by lieuwex** [comment]
There could be differences, what's different and is it a problem? I tried to make the returned content kinda as it would be rendered inside of Magister, limiting the amount of newlines inbetween the lines and stuff.

I will rebase

**Pull request merged**
